apiVersion: v1
kind: PersistentVolume
metadata:
  name: sc-volume
spec:
  storageClassName: "sc-storage"
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: sc-volume-claim
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/seacontact/regions/us-east4/disks/sc-disk-neo4j
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: sc-volume-claim
spec:
  storageClassName: "sc-storage"
  volumeName: sc-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
