mutation AddComment($data: AddCommentInput!) {
	AddComment(data: $data) {
		__typename
		... on Comment {
			topic {
				__typename
				... on Question {
					comments(orderBy: timestamp_asc) {
						...commentFields
					}
				}
				... on Answer {
					comments(orderBy: timestamp_asc) {
						...commentFields
					}
				}
			}
		}
		... on FormError {
			...formErrorFields
		}
	}
}
