query QuestionPage($nodeId: ID!) {
	Question(nodeId: $nodeId) {
		nodeId
		title
		text
		viewsCount
		author {
			...userFields
		}
		tags {
			nodeId
			name
		}
		createdAt {
			...dateTimeFields
		}

		answersCount
		answers(orderBy: timestamp_asc) {
			...answerFields
		}

		canSubscribe
		isSubscribed
		subscribersCount

		canComment
		commentsCount
		comments(orderBy: timestamp_asc) {
			...commentFields
		}
	}
}
