query QuestionsList(
	$orderBy: [_QuestionOrdering]
	$first: Int
	$offset: Int
	$filter: _QuestionFilter
) {
	Question(orderBy: $orderBy, first: $first, offset: $offset, filter: $filter) {
		nodeId
		title
		text
		author {
			nodeId
			name
			surname
			rank
		}
		viewsCount
		answersCount
		subscribersCount
		commentsCount
		createdAt {
			year
			month
			day
			hour
			minute
		}
		tags(first: 5) {
			nodeId
			name
		}
	}
}
