version: '3'

services:
  as-neo4j:
    image: 'neo4j:4.2.2-enterprise'
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true

  api:
    build: ./api
    # restart: unless-stopped
    command: sh -c "cd /api/ && npm install && npm run start" # dev option
    ports:
      - 4000:4000
    volumes:
      - ./api:/api
      # - /api/node_modules # prod option (hide node modules folder)
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_ENCRYPTED=${NEO4J_ENCRYPTED}
      - GRAPHQL_SERVER_PORT=${GRAPHQL_SERVER_PORT}
      - GRAPHQL_SERVER_PATH=${GRAPHQL_SERVER_PATH}
      - GRAPHQL_SERVER_HOST=${GRAPHQL_SERVER_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - DEFAULT_ROLE=${DEFAULT_ROLE}
    links:
      - as-neo4j
    depends_on:
      - as-neo4j
## in docker-compose v2:
# mem_limit: 2G
# memswap_limit: 3G
# mem_reservation: 1G
