mutation Register($data: RegisterUserInput!) {
	Register(data: $data) {
		__typename
		... on TokenResponse {
			token
		}
		... on FormError {
			message
			errors {
				field
				message
			}
		}
	}
}
