enum VoteIntention {
	upVote
	downVote
}

enum UserRank {
	CHIEF_OFFICER
	RADIO_OFFICER
	SINGLE_OFFICER
	S2ND_OFFICER
	T3RD_OFFICER
	SENIOR_DPO
	JUNIOR_DPO
	DPO
	TRAINEE_OFFICER
	BOSUN_BOATSWAIN
	AB_ABLE_SEAMAN
	OS_ORDINARY_SEAMAN
	CRANE_OPERATOR
	DREDGE_MASTER
	DECK_CADET
	COOK
	MESSBOY
	ABCOOK
	ABWELDER
	CADETTRAINEE
	CHIEF_ENGINEER
	SINGLE_ENGINEER
	S2ND_ENGINEER
	T3RD_ENGINEER
	F4TH_ENGINEER
	REF_ENGINEER
	GAS_ENGINEER
	ELECTRICAL_ENGINEER
	ETO_
	TRAINEE_ENGINEER
	MOTORMANOILER
	FITTERWELDER
	TURNER
	ELECTRICIAN
	PUMPMAN
	ENGINE_CADET
	SUPERINTENDENT
	ABMM
	CHIEF_COOK
	S2ND_COOK
	DIVER
	WIPER
	MOTORMANELECTRICIAN
	ASSISTANT_ELECTRICAL_ENGINEER
	WATCH_ENGINEER
	STAFF_ENGINEER
	HOTEL_ACCOMMODATION_ENGINEER
	STEWARDESS
	HYDRO_ACOUSTIC_OPERATOR
	CHIEF_TRAWL_MASTER
	WATCH_TRAWL_MASTER
	SEAMAN_WINCHMAN
	TRAWL_SEAMAN
	MASTER_OF_THE_PRODUCT
	FISH_MASTER
	WORKERS_OF_THE_PRODUCT_PLANT
	ENGINEER_ADJUSTER
	FISHMILL_OPERATOR
	REFRIGERATOR_OPERATOR
	LAUNDRY_OPERATOR
	GENERAL_MANAGER
	HOTEL_MANAGER
	CASINO_MANAGER
	SHOP_MANAGER
	PROVISION_MASTER
	STORE_MANAGER
	PURSER
	ACCOUNTANT
	CRUISE_DIRECTOR
	HOTEL_MANAGER_DIRECTOR
	HOTEL_MANAGER_SECRETARY
	RECEPTIONIST
	STOREKEEPER
	CASHIER
	PHOTOGRAPHER
	SECURITY_OFFICER
	SECURITY_GUARD
	STEWARD_HEAD_ROOM
	STEWARDSTEWARDESS_CABIN
	STEWARDSTEWARDESS_ASSISTANT_CABIN
	BELL_CAPTAIN
	BELL_BOY
	CLEANER
	LAUNDRY_MAN
	LINEN_KEEPER
	CHAMBERMAID
	POOL_ATTENDANT
	FOODBEVERAGE_MANAGER
	FOODBEVERAGE_ASSISTANT_MANAGER
	BAR_MANAGER
	BAR_ASSISTANT_MANAGER
	BARTENDER
	BAR_WAITER
	HEAD_WAITER
	WAITERWAITRESS
	WINE_STEWARD
	BUSBOY
	PLUMBER
	UPHOLSTERER
	TAILOR
	CARPENTER
	AC_REPAIRMAN
	GENERAL_PURPOSE_REPAIRMAN
	DOCTOR
	ADMINISTRATIVE_ASSISTANT
	ART_AUCTIONEER
	ASSISTANT_CRUISE_DIRECTOR
	ASSISTANT_SHORE_EXCURSIONS_MANAGER
	AUDIO_VISUAL_COORDINATOR
	AVIT
	BAKER
	BAR_STEWARD
	BEAUTICIAN
	BEAUTY_THERAPIST
	BEDROOM_STEWARD
	BOOKING_AGENT
	BOOKKEEPER
	BRAND_MANAGER
	BUFFET_SERVER
	BUTCHER
	CABIN_STEWARDESS
	CETO
	CHEF_DE_PARTIE
	CHIEF_CABIN_STEWARD
	CHIEF_PURSER
	CHIEF_STEWARDHOUSEKEEPER
	CHIEF_STEWARDESS
	COCKTAIL_SERVER_
	COMPUTER_SYSTEMS_MANAGERIT
	COSMETOLOGIST
	CRUISE_CONSULTANT
	CUSTOMER_SERVICE_REPRESENTATIVE
	DANCER
	DANCE_INSTRUCTOR
	DECK_HAND
	DINING_ROOM_HEAD_WAITER
	DINING_ROOM_MANAGER
	DISC_JOCKEY
	DIVE_INSTRUCTOR
	ENTERTAINER
	EXPEDITION_LEADER
	FIELD_REPRESENTATIVE
	FITNESS_DIRECTOR
	FITNESS_INSTRUCTOR
	GALLEY_STEWARDESS
	GENERAL_COOK
	GENTLEMEN_HOST
	GIFT_SHOP_MANAGER
	GIFT_SHOP_SALES_ASSISTANT
	HAIR_STYLIST
	HOUSEKEEPER_ASSISTANT
	HOUSEKEEPER_CHIEF
	HR_MANAGER
	INSIDE_SALES_REPRESENTATIVE
	IT_LEAD_DEVELOPER
	IT_STAFF
	LAUNDRY_HELPER
	LAUNDRY_KEEPER
	LAUNDRY_SUPERVISOR
	LEAD_DECKHAND_
	LECTURER_SPECIAL_GUEST_SPEAKER
	LIFEGUARD
	MAITRE_D_HOTEL
	MANICURIST
	MARKETINGPR
	MARKETING_RESEARCH_ANALYST
	MASSAGE_THERAPIST
	NATURALIST
	NURSESTEWARDESS
	OPERATIONS_ADMINISTRATOR
	OPERATIONS_ANALYST
	OUTSIDE_SALES_REPRESENTATIVE
	PAYROLL_CLERK
	PERSONAL_TRAINER
	PRODUCTION_MANAGER
	PROGRAM_COORDINATOR
	PURCHASING_AGENT
	QUARTER_MASTER
	SAFETY_OFFICER
	SENIOR_BUSINESS_ANALYST
	SENIOR_HOUSEKEEPER
	SENIOR_STAFF_ACCOUNTANT
	SENIOR_STEWARDESS
	SHORE_EXCURSIONS_MANAGER
	SOCIAL_HOSTHOSTESS
	SOFTWARE_ENGINEER
	SOUND_AND_LIGHT_TECHNICIAN
	SPA_ATTENDANT
	SPA_STEWARDESS
	STAFF_ACCOUNTANT
	STAFF_CAPTAIN
	TOUR_ACCOUNTING
	WATER_SPORTS_INSTRUCTOR
	WORKER_OF_THE_PRODUCT_PLANT
	CONTRACTS_ADMINISTRATOR
	CONTRACTS_MANAGER
	CHARTERING_MANAGER
	SYSTEMS_ENGINEER
	NAVAL_ARCHITECT
	SALES_MANAGER
	BUSINESS_DEVELOPMENT_MANAGER
	SUPERINTENDENT_ELECTRICAL
	TRADER
	ANALYST
	PORT_MANAGER
	ENGINEERING_MANAGER
	MAINTENANCE_TECHNICIAN
	CAD_OPERATOR
	SG1A
	SERVICE_MANAGER
	TECHNICAL_MANAGER
	UNDERWRITER
	HEAD_OF_NETWORK_PLANNING
	NETWORK_PLANNING_MANAGER
	MARINE_SURVEYOR
	MARINE_CONSULTANT
	BUYER
	TERMINAL_MANAGER
	SUPERINTENDENT_TECHNICAL
	IT_MANAGER
	TECHNICAL_ASSISTANT
	OPERATIONS_MANAGER
	SHIP_PLANNER
	MARINE_MANAGER
	ASSOCIATE
	SHIP_OPERATOR
	CREWING_MANAGER
	SERVICE_ENGINEER
	CONTROLS_ENGINEER
	ACCOUNT_EXECUTIVE
	CLAIMS_EXECUTIVE
	RISK_ADVISOR
	ACCOUNT_MANAGER
	COMMERCIAL_MANAGER
	HUMAN_RESOURCES
	WELDING_ENGINEER
	EXPORT_CLERK
	PROJECT_MANAGER
	VETTING_SUPERINTENDENT
	PROCUREMENT_OFFICER
	SUPERINTENDENT_OPERATIONS
	OPERATIONS_ASSISTANT
	OPERATIONS_EXECUTIVE
	LOGISTICS_EXECUTIVE
	QUALITY_MANAGER
	MARINE_ENGINEER
	OPERATIONS_OFFICER
	SALES_ENGINEER
	CARGO_ENGINEER
	TECHNICAL_DIRECTOR
	PROCUREMENT_MANAGER
	CUSTOMER_SERVICE_EXECUTIVE
	BUNKER_PURCHASER
	PROJECT_ENGINEER
	BUNKER_TRADER
	RECRUITMENT_CONSULTANT
	STRUCTURAL_ENGINEER
	PROJECT_OFFICER
	PORT_ENGINEER
	CLIENT_REPRESENTATIVE
	SHIPS_AGENT
	PORT_AGENT
	CHARTERER
	SUPERINTENDENT_CARGO
	CREWING_OFFICER
	OPERATIONS_DIRECTOR
	ASSISTANT_HSE_SUPERINTENDENT
	ENVIRONMENTAL_MANAGER
	MARKETING_EXECUTIVE
	PORT_CAPTAIN
	BROKER
	HSE_MANAGER
	SURVEYOR
	ADMINISTRATION_MANAGER
	ROUSTABOUT
	DERRICKMAN
	FLOOR_MAN
	PIPEFITTER
	FABRICATOR
	COXSWAIN
	REPAIR_ENGINEER
	PERSONAL_ASSISTANT_SECRETARY
	ADMINISTRATION_SUPPORT
	INJECTION_MOLDING_MACHINE_OPERATOR
	JUNIOR_MECHANICAL_ENGINEER
	SPRING_MACHINE_OPERATOR
	LATHE_MACHINE_OPERATOR
	SLOT_TECHNICIAN
	COMMISSIONING_ENGINEER
	COMMUNICATION_OFFICER
	HYDROGRAPHIC_SURVEYOR
	PIPE_OPERATOR
}

enum Role {
	user
	admin
	reader
}

enum ResponseStatus {
	success
	fail
}
