interface CanBeCommented {
	nodeId: ID!
	commentsCount: Int
	comments: [Comment]
}

interface CanBeLiked {
	nodeId: ID!
	likes: [User]
	likesCount: Int
	canLike: Boolean
}

interface CanBeSubscribed {
	nodeId: ID!
	subscribersCount: Int
	subscribers: [User]
}

interface CanBeVoted {
	nodeId: ID!
	upVotesCount: Int
	downVotesCount: Int
	canVote: Boolean
	canVoteUp: Boolean
	canVoteDown: Boolean
}
