mutation ToggleSubscribe($data: nodeIdInput!) {
	ToggleSubscribe(data: $data) {
		__typename
		... on Question {
			nodeId
			subscribersCount
		}
		... on Tag {
			nodeId
			subscribersCount
		}
	}
}
