type Answer implements CanBeCommented & CanBeVoted {
	nodeId: ID! @id
	text: String!
	createdAt: DateTime
	updatedAt: DateTime
	timestamp: String
	author: User! @relation(name: "ANSWERED", direction: IN)
	question: Question! @relation(name: "HAS_ANSWER", direction: IN)

	canAccept: Boolean
		@isAuthenticated
		@cypher(
			statement: "MATCH (u:User {nodeId: $cypherParams.currentUserId})-[:ASKED]->(:Question)-[:HAS_ANSWER]->(this) RETURN count(u) > 0 as canAccept"
		)
	accepted: Boolean
		@cypher(
			statement: "MATCH (this)<-[r:ACCEPTED]-(:User) RETURN count(r) > 0 as accepted"
		)

	comments: [Comment] @relation(name: "HAS_COMMENT", direction: OUT)
	commentsCount: Int
		@cypher(
			statement: "RETURN size((this)-[:HAS_COMMENT]->(:Comment)) as commentsCount"
		)
	canComment: Boolean
		@cypher(
			statement: "MATCH (u:User {nodeId: $cypherParams.currentUserId}) RETURN count(u) = 1 as canComment"
		)
	canDelete: Boolean
		@cypher(
			statement: "RETURN size((this)<-[:ANSWERED]-(:User {nodeId: $cypherParams.currentUserId})) as canDelete"
		)

	canVote: Boolean
		@cypher(
			statement: "MATCH (u:User {nodeId: $cypherParams.currentUserId}) RETURN count(u) = 1 as canSubscribe"
		)
	isVotedUp: Boolean
		@cypher(
			statement: "MATCH (this)<-[r:VOTED_UP]-(:User {nodeId: $cypherParams.currentUserId}) RETURN count(r) > 0 as isVotedUp"
		)
	isVotedDown: Boolean
		@cypher(
			statement: "MATCH (this)<-[r:VOTED_DOWN]-(:User {nodeId: $cypherParams.currentUserId}) RETURN count(r) > 0 as isVotedDown"
		)
	upVotesCount: Int
		@cypher(
			statement: "RETURN size((this)<-[:VOTED_UP]-(:User)) as upVotesCount"
		)
	downVotesCount: Int
		@cypher(
			statement: "RETURN size((this)<-[:VOTED_DOWN]-(:User)) as downVotesCount"
		)
}

type Mutation {
	AnswerQuestion(data: AnswerQuestionInput!): AnswerQuestionResponse!
		@isAuthenticated
		@cypher(
			statement: """
			MATCH (u:User {nodeId: $cypherParams.currentUserId})
			CREATE (a:Answer:CanBeCommented:CanBeVoted)<-[:ANSWERED]-(u)
			SET a += {
				text: $data.text,
				nodeId: apoc.create.uuid(),
				createdAt: DateTime(),
				timestamp: timestamp()
			}
			WITH a
			MATCH (q:Question {nodeId: $data.nodeId})
			CREATE (q)-[r:HAS_ANSWER]->(a)
			RETURN a
			"""
		)

	EditAnswer(data: EditAnswerInput!): Answer!
		@isAuthenticated
		@cypher(
			statement: """
			MATCH (a:Answer {nodeId: $data.nodeId})<-[:ANSWERED]-(u:User {nodeId: $cypherParams.currentUserId})
			SET a += {text: $data.text, updatedAt: DateTime()}
			RETURN a
			"""
		)

	#TODO: Delete related comments
	DeleteAnswer(data: nodeIdInput!): DeleteAnswerResponse!
		@isAuthenticated
		@cypher(
			statement: """
			MATCH (a:Answer {nodeId: $data.nodeId})<-[:ANSWERED]-(u:User {nodeId: $cypherParams.currentUserId})
			WITH a, properties(a) AS m
			DETACH DELETE a
			RETURN m
			"""
		)

	ToggleAcceptAnswer(data: nodeIdInput!): Answer
		@isAuthenticated
		@cypher(
			statement: """
			MATCH (u:User {nodeId: $cypherParams.currentUserId})-[:ASKED]->(:Question)-[:HAS_ANSWER]->(t:Answer {nodeId: $data.nodeId})
				CREATE (u)-[:ACCEPTED]->(t)
				WITH u, t
			CALL {
				MATCH (u)-[r:ACCEPTED]->(t), (u)-[:ACCEPTED]->(t)
				DELETE r
				RETURN t as g
				UNION
				MATCH (g:Answer {nodeId: $data.nodeId})
				RETURN  g
			}
			RETURN g
			"""
		)
}
