query TagPage($name: String) {
	Tag(name: $name) {
		...tagFields
		description
		questionsSolvedCount
		moderators {
			...userFields
		}
		topUsers {
			...userFields
		}
		topQuestions {
			...questionListItemFields
		}
	}
}
