query UserPage($nodeId: ID!) {
	User(nodeId: $nodeId) {
		...userFields
		email
		location
		questionsCount
		answersCount
		solvedQuestionsCount
		favoriteTags {
			...tagFields
		}
		questions {
			nodeId
			title
			text
			author {
				...userFields
			}
			createdAt {
				...dateTimeFields
			}
			tags(first: 5) {
				nodeId
				name
			}
			viewsCount
			answersCount
			commentsCount

			canSubscribe
			isSubscribed
			subscribersCount
		}
	}
}
