query UserPage($nodeId: ID!) {
	User(nodeId: $nodeId) {
		...userFields
		email
		location
		questionsCount
		answersCount
		questionsSolvedCount
		favoriteTags {
			...tagFields
		}
		questions {
			...questionListItemFields
		}
	}
}
