fragment userFields on User {
	nodeId
	name
	surname
	rank
	description
}

fragment commentFields on Comment {
	nodeId
	text
	likesCount
	isLiked
	canLike
	createdAt {
		...dateTimeFields
	}
	author {
		...userFields
	}
}

fragment answerFields on Answer {
	nodeId
	text
	author {
		...userFields
	}
	createdAt {
		...dateTimeFields
	}
	comments(orderBy: timestamp_asc) {
		...commentFields
	}

	canVote
	upVotesCount
	downVotesCount
	isVotedUp
	isVotedDown

	canComment
	commentsCount
}

fragment formErrorFields on FormError {
	message
	errors {
		message
		field
	}
}

fragment dateTimeFields on _Neo4jDateTime {
	year
	month
	day
	hour
	minute
}
