query QuestionsList(
	$orderBy: [_QuestionOrdering]
	$first: Int
	$offset: Int
	$filter: _QuestionFilter
	$tagsCount: Int = 5
) {
	Question(orderBy: $orderBy, first: $first, offset: $offset, filter: $filter) {
		nodeId
		title
		text
		author {
			...userFields
		}
		createdAt {
			...dateTimeFields
		}
		tags(first: $tagsCount) {
			nodeId
			name
		}
		viewsCount
		answersCount
		commentsCount

		canSubscribe
		isSubscribed
		subscribersCount
	}
	QuestionCount(filter: $filter) {
		totalCount
	}
}
