query QuestionPage($nodeId: ID!) {
	Question(nodeId: $nodeId) {
		nodeId
		title
		text
		author {
			...userFields
		}
		tags {
			nodeId
			name
		}
		comments(orderBy: createdAt_asc) {
			...commentFields
		}
		answers {
			nodeId
			text
			upVotesCount
			downVotesCount
			commentsCount
			createdAt {
				...dateTimeFields
			}
			author {
				...userFields
			}
			comments {
				...commentFields
			}
		}
		createdAt {
			...dateTimeFields
		}
		viewsCount
		upVotesCount
		downVotesCount
		subscribersCount
		answersCount
		commentsCount
	}
}
