mutation EditProfile($data: UserProfileInput!) {
	EditProfile(data: $data) {
		__typename
		... on Profile {
			name
			surname
			avatar
			rank
			description
			isPasswordChanged
		}
		... on FormError {
			...formErrorFields
		}
	}
}
